project:
  type: website
  output-dir: docs

website:
  title: "Yuvraaj Singh Kohli's MBA Portfolio"
  description: "Professional portfolio showcasing education, experience, projects, and skills."
  navbar:
    title: "Portfolio"
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "GitHub"
        href: https://github.com/Yuvik-hub

format:
  html:
    theme: default
    css: styles.css
    toc: true
